### ISSUE TITLE
Feature Request: Allow full pane view

### ISSUE THREAD

**Issue by mediapathic** [sandorex/set-in-obsidian-plugin#4]
I am very excited about this plugin, I love where it's going. However, on my smaller screen the week and month views are mostly unusable in the narrow sidebars. I would find this far more functional if I could view it in a main pane. An even better, but probably more difficult to implement, solution would be to have the timeline available as an embeddable code block, which would allow things like having a timeline visible within my week planning note. 

Thank you!

**Comment by sandorex** [comment]
That's an interesting idea, ill see what i can do although i cant give any ETA

Fullscreen mode shouldn't be hard though

**Comment by sandorex** [comment]
You should now be able to drag the timeline in center and use it fullscreen

**Comment by mediapathic** [comment]
Wow, that was quick! I guess no eta was needed :) Thank you!

**Comment by sandorex** [comment]
It was a simple fix, also working on embedding the calendar as the idea seems interesting

![image](https://user-images.githubusercontent.com/18004075/210850691-27c15514-2161-45db-bd88-fe17789a6b87.png)

**Comment by sandorex** [comment]
I've added embedded calendar in commit https://github.com/sandorex/set-in-obsidian-plugin/commit/6c2d6e226173714c0138715e0fb32c928ec8aa23 (release [#1.0.13](https://github.com/sandorex/set-in-obsidian-plugin/releases/tag/1.0.13))
