### ISSUE TITLE
Display events for a static date possible?

### ISSUE THREAD

**Issue by NothingWorksToday** [sandorex/set-in-obsidian-plugin#5]
**Use Case**
I want to save all my events in a single note and display all relevant events scheduled for a specific day on a daily note.

**Issue**
Currently when I integrate the code into my daily note, it always displays events for the current date (the date I'm looking at the note), not for the date the note is for (could be future/past).

**Proposal**
Allow the code to display events for a static date, maybe passed as an argument.

**Comment by sandorex** [comment]
It's possible but not practical for the global calendar, for embedded calendar

``````
```set-in-obsidian-minimal
{
    "defaultView": "listDay",
    "fullcalendar": {
        "initialDate": "2023-01-01"
    },
    "useThisFile": true
}
```
``````

Where `defaultView` can be any option fullcalendar supports, for more information check out https://fullcalendar.io/docs#toc

**Do note that embeded calendars are not automatically updated so you either have to reload the file or edit the code block**

Feel free to reopen if this does not solve your usecase

**Comment by NothingWorksToday** [comment]
Thanks, this solves my usecase!
